### ISSUE TITLE
Plugin breaks image remove link in task

### ISSUE THREAD

**Issue by msapalas** [BlueTeck/kanboard_plugin_coverimage#16]
After plugin installed, it breaks image remove function in task. Issue is that class "popover" has been added to link and modal window stops working properly.

Solution: remove class "popover" from the links in the /plugins/Coverimage/Template/task_file/images.php lines 10 and 23.

Tested on Kanboard v. 1.0.38

**Comment by TimoStahl** [comment]
Hi,
thanks for reporting this.

I've created a new release (ready for manual install).

It will be availiable for automatic install as soon as this pull request is merged: 
https://github.com/kanboard/website/pull/25

Regards,
Timo
