### ISSUE TITLE
overflow should be hidden?

### ISSUE THREAD

**Issue by thob** [BlueTeck/kanboard_plugin_coverimage#17]
Hi, seems a css command might help, it happens on smaller screens
![coveroverflow](https://cloud.githubusercontent.com/assets/755337/23473183/9351393c-feaf-11e6-91a7-846710f17aec.png)

**Comment by TimoStahl** [comment]
This should not happen:

https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/master/assets/css/board.css#L10

I will test again and look into it, thanks for reporting.

**Comment by TimoStahl** [comment]
I am sorry, but I cannot reproduce your issue.

Which Kanboard version and which browser are you using?

**Comment by thob** [comment]
Kanboard 1.0.40
Chrome 56.0.2924.87 (64-bit) / Linux Mint 17.3

_Just checked it again_

**Comment by creecros** [comment]
Spun up v1.0.40 test server and tried to reproduce:

![image](https://raw.githubusercontent.com/creecros/empty/master/test_coverimage.gif)

Couldn't reproduce.

My guess, there is another Plugin that's conflicting with the CSS. Taking notice to your corners versus what they should be, seems likely that is the case. 

Your corner in board view:
![image](https://user-images.githubusercontent.com/26339368/46437828-454c9200-c72a-11e8-963c-588b2b1a4e43.png)

What the corner should be:
![image](https://user-images.githubusercontent.com/26339368/46437839-50072700-c72a-11e8-827b-38502e40a253.png)


What plugins are installed?
