### ISSUE TITLE
Images disappear

### ISSUE THREAD

**Issue by ChangePlaces** [BlueTeck/kanboard_plugin_coverimage#18]
After installing - master and latest release, there are no images being shown in the the task view

**Comment by ChangePlaces** [comment]
Plugin directory MUST be called Coverimage - I had it as CoverImage. the casing should be fixed

**Comment by TimoStahl** [comment]
What should I fix? The Readsme says: Create a folder plugins/Coverimage

**Comment by ChangePlaces** [comment]
sure, but cover and image are two words, so the capitilisation should be CoverImage
