### ISSUE TITLE
Attached jpg files invisibles with coverimage activated

### ISSUE THREAD

**Issue by tutle** [BlueTeck/kanboard_plugin_coverimage#19]
On kanboard 1.0.46, I've desactivated extension coverimage and the pictures are back. 
Otherwise, they are invisibles (see pictures)
![kanboard jpg bug 1](https://user-images.githubusercontent.com/23037149/30421079-f997bdfc-993b-11e7-8a51-0e9d56d99100.PNG)
![kanboard jpg bug 2](https://user-images.githubusercontent.com/23037149/30421080-f9991e5e-993b-11e7-9284-ff8817dfd2d5.PNG)
I really don't know why...

**Comment by TimoStahl** [comment]
Unfortunately I can't reproduce your issue, everything is working fine for me.

Could you try to comment/remove this line in Plugin.php: 
```php
$this->template->setTemplateOverride('task_file/images', 'coverimage:task_file/images');
```

https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/master/Plugin.php#L12

An check if the image still disapears in the task detail page.
