### ISSUE TITLE
not showing up in install plugin listing for mysql installation

### ISSUE THREAD

**Issue by lastlink** [BlueTeck/kanboard_plugin_coverimage#20]
Kanboard 1.2.0
Mysql db.

I wonder if having a ">=" is the reason for this.

In https://github.com/kanboard/website/blob/master/plugins.json
you give `"compatible_version": "1.0.38"`
while most other plugins did this
`"compatible_version": ">=1.0.32".`
Your plugin isn't appearing in my installation. I have a sqlite & postgres sandbox installation same kanbaord version & it's showing up in the plugin directory, but not on mysql.

**Comment by TimoStahl** [comment]
Oh, thanks, lets try :)

https://github.com/kanboard/website/pull/15

**Comment by lastlink** [comment]
showing up now in my installation
