### ISSUE TITLE
Can't set a cover image 

### ISSUE THREAD

**Issue by RoiArthurB** [BlueTeck/kanboard_plugin_coverimage#26]
Hi, I installed the plugin from the plugin installer and I can't set image as covering...

![image](https://user-images.githubusercontent.com/16764085/79711673-ab8c0c00-82f2-11ea-8d5b-aa0b485206f3.png)

**About**
Configuration : 
![Kanboard 1.2.14](https://user-images.githubusercontent.com/16764085/79711767-fc036980-82f2-11ea-9753-e9bdb1e5c844.png)

Coverimage version : 1.2.14.0

**Comment by TimoStahl** [comment]
Bug is fixed, and waiting for the installer to be updated (https://github.com/kanboard/website/pull/232).

Otherwise you could download the latest release manually https://github.com/BlueTeck/kanboard_plugin_coverimage/releases

**Comment by RoiArthurB** [comment]
Ok thanks you're the best ! 💪💪💪

**Comment by RoiArthurB** [comment]
Perfect now 😗
![image](https://user-images.githubusercontent.com/16764085/79824551-b01ef600-83c0-11ea-8282-7ccf2b2a5b59.png)
