### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by thob** [BlueTeck/kanboard_plugin_coverimage#3]

**Comment by TimoStahl** [comment]
Here are two screenshots: https://github.com/fguillot/kanboard/issues/307#issuecomment-199436002

Maybe I should enhance the readme and add pictures ;)

**Comment by thob** [comment]
Ahh!
- is it supposed to pop up on click? It doesn't here.

**Comment by kierun** [comment]
^_~ Enhancing the readme and adding pictures would be grand! I thought this provided some background image on the boards… Not that the current feature it not useful, it is and I am happy to have it installed.

**Comment by TimoStahl** [comment]
I've added a screenshot to the readme

https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/master/README.md
