### ISSUE TITLE
Text in popup menu

### ISSUE THREAD

**Issue by artur-shaik** [BlueTeck/kanboard_plugin_coverimage#31]
https://github.com/BlueTeck/kanboard_plugin_coverimage/blob/0559c135e009044e305f25a8a6e7243ab28669af/Locale/ru_RU/translations.php#L10

I'm just wonder, shouldn't it start with capital letter?

![image](https://user-images.githubusercontent.com/4862907/109111289-d9d44680-7762-11eb-8c7e-f2b935fc9c26.png)

**Comment by TimoStahl** [comment]
@dmkcv has done the RU translation, I don't speak it  😄

**Comment by artur-shaik** [comment]
Yeah, but as I can see, this approach is in original, too.

![image](https://user-images.githubusercontent.com/4862907/109115605-81ed0e00-7769-11eb-9e45-5d0846a45bce.png)

**Comment by TimoStahl** [comment]
You are right, I've changed it 😀

**Comment by artur-shaik** [comment]
Thank you! :smile:
