### ISSUE TITLE
Plugin crash kb on install

### ISSUE THREAD

**Issue by auguster** [BlueTeck/kanboard_plugin_coverimage#4]
I tried to install your plugin through the extensions manager in kanboard, it just crashed everything and just display:
`Internal Error: Unable to load this plugin class \Kanboard\Plugin\kanboard_plugin_coverimage-1.0.29.0\Plugin`

Luckily I can recover from that by deleting the plugin manually.

I'm running kanboard 1.0.29 in a docker container built using the official dockerfile.

**Comment by auguster** [comment]
Out of the blue, I renamed the folder `kanboard_plugin_coverimage-1.0.29.0` to `Coverimage` and it worked...

**Comment by TimoStahl** [comment]
I will check it later today, maybe there is something wrong with the new plugin manager (or my implementation of the autoinstall)

Thanks for reporting

**Comment by szawadski** [comment]
Thanks for the workaround!

**Comment by TimoStahl** [comment]
Should be fixed if this pull request is merged

https://github.com/kanboard/website/pull/7/files

**Comment by TimoStahl** [comment]
fixed
