### ISSUE TITLE
doesn't work with 1.0.31

### ISSUE THREAD

**Issue by thob** [BlueTeck/kanboard_plugin_coverimage#7]

**Comment by TimoStahl** [comment]
Could you please specify your error, for me it is working.

**Comment by thob** [comment]
sorry, the error was
`Internal Error: Identifier "language" is not defined`

**Comment by TimoStahl** [comment]
Are you using the latest plugin version?

**Comment by thob** [comment]
Ohh, no. Got it from https://kanboard.net/plugins. The latest is working fine

**Comment by TimoStahl** [comment]
I've created a pull request for the kanboard website, after the merge, the newest version of the plugin is linked there.

https://github.com/kanboard/website/pull/7
